### ISSUE TITLE
[FIXED] Wishlist

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#907]
- [ ] Create a MULTI OUT VST Plugin. See #1
***
- [ ] midi implementation for the volume, pan and metro knobs and faders? See #13
***
- [ ] Create a forum in the website #17
***
- [ ] native plugins
***
- [ ] Add a button "check server mix". See #34
***
- [ ] 32 bits VST wrapper
***
- [ ] Add a ComboBox in Preferences Panel to select the default midi device. See #52
***
- [ ] VST racks for the other musicians in a server. See #108
***
- [ ] Midi CC implementation for vst plugins' Knobs and Faders. See #169
***
- [ ] Native Limiter Implementation. See #232
***
- [ ] Chord Progressions/songs database. See #236
***
- [ ] Separate local monitor mix. Details in #392
***
- [ ] Quick hyper Preset Buttons. Details in #428
***
- [ ] Add "Chord Image Viewer" to display chords graphically. Details in #504
***
- [ ] PANIC button for Midi tracks [Standalone]. Details in #714
***
- [ ] [Looper] Manage uncommon wave file formats. Magnus reported some wave audio file formats are not loaded in looper. Some unloadable files in [https://www.dropbox.com/sh/6glmjp3cl8p2czo/AAC9X1V65nsiMeKhfGBil2_ra?dl=0](https://www.dropbox.com/sh/6glmjp3cl8p2czo/AAC9X1V65nsiMeKhfGBil2_ra?dl=0)

***
- [ ] Graphic tool to write/edit chord sequences. Details in #801
***
- [ ] [Looper] Frippertronics mode or checkbox for selected mode. Details in #826
***
- [ ] Common Room ambiance. Detais in #856
***
- [x] Network Bandwidth meter
***
- [ ] Jamtaba for Android
***
- [ ] AI based Jams (proposed by Qulf):
> Hi all. i Have fun idea. I found that on youtube https://www.youtube.com/watch?v=QlVoR1jQrPk
> and that is here [https://github.com/tensorflow/magenta-demos](https://github.com/tensorflow/magenta-demos)  
> Could it be possible to connect to jamtaba?
***
- [ ] Use the looper without connect in a server
***
- [ ] Is there a way to set the metro indicator to just be a single line  with all the beats visible?
I think seeing the entire line helps me time stuff. 
***
- [x] Continuous Integration. See #216
